/* DEMO PROJECT — "A Hand in the Dark" (opening 6 shots). Used by "Load demo" in the app. */
window.DEMO = {
  title: 'A Hand in the Dark',
  script: "Thirty metres under the sea, a diver swims into a sunken tugboat. He is looking for bodies. Then a hand reaches out of the dark, and grabs him. The hand is alive. Rewind sixty hours. Harrison Okene, the ship's cook, is trapped in an air pocket.",
  plan: {
    title: 'A Hand in the Dark', sky: 'night',
    assets: [
      { name: 'diver', kind: 'character', difficulty: 3, size: 3, look: 'Rescue diver: hero build, round glass helmet, air tank on his back, dark teal suit.', parts: ['helmet', 'tank'], moves: [] },
      { name: 'okene', kind: 'character', difficulty: 2, size: 2.4, look: 'Ship cook: pear build, short hair, cream tee, brown trousers, big nose.', parts: [], moves: [] },
      { name: 'reaching-hand', kind: 'prop', difficulty: 1, size: 1, look: 'A lone arm coming out of darkness, palm open.', parts: ['arm'], moves: ['reach'] },
      { name: 'torch', kind: 'prop', difficulty: 1, size: .5, holdable: true, look: 'Diving torch with a warm glow at the front.', parts: ['grip'], moves: [] },
      { name: 'cabin', kind: 'set', difficulty: 2, size: 14, look: 'Sunken tugboat cabin: dark panels, pipes, a round porthole glow, water ceiling.', parts: ['spots'], moves: [], spots: ['door', 'center', 'corner', 'pocket'] }
    ],
    cuts: {
      main: [
        { id: 'S01', lines: [0, 1], set: 'cabin', cast: ['diver', 'torch'], show: 'Wide: the diver swims in through the door with his torch.', mood: 'cold', difficulty: 2 },
        { id: 'S02', lines: [2, 2], set: 'cabin', cast: ['diver', 'torch'], show: 'Medium: the diver looks around slowly.', mood: 'dark', difficulty: 1 },
        { id: 'S03', lines: [3, 4], set: 'cabin', cast: ['diver', 'reaching-hand', 'torch'], show: 'A hand reaches out of the dark and grabs him. He jumps.', mood: 'danger', difficulty: 2 },
        { id: 'S04', lines: [5, 5], set: 'cabin', cast: ['diver'], show: 'Close-up: his shocked face.', mood: 'danger', difficulty: 1 },
        { id: 'S05', lines: [6, 6], set: 'void', cast: [], show: 'Title card: 60 HOURS EARLIER.', mood: 'silhouette', difficulty: 1 },
        { id: 'S06', lines: [7, 8], set: 'cabin', cast: ['okene'], show: 'Okene alone in the air pocket, scared, water up to his chest.', mood: 'dark', difficulty: 1 }
      ]
    }
  },
  assets: {
    'diver': "KIT.asset('diver', function (K, opts) {\n  var rig = K.human({ build: 'hero', skin: K.PAL.skin[1], hair: K.PAL.hair[0], hairStyle: 'short', top: 'tee', shirt: K.PAL.teal, pants: K.PAL.charcoal, nose: 1.2 });\n  var helmet = new K.T.Group(); helmet.position.set(0, .44, 0); rig.head.add(helmet);\n  K.flat(K.SPH, K.PAL.glowMoon, helmet, 0, 0, 0, .58, .6, .58, .18);\n  K.M(new K.T.TorusGeometry(.5, .05, 10, 32), K.PAL.mustard, helmet, 0, -.38, 0, 1, 1, 1, 'thin').rotation.x = Math.PI / 2;\n  var tank = new K.T.Group(); tank.position.set(0, .55, -.62); rig.torso.add(tank);\n  K.M(K.lathe([[0, 0], [.2, .04], [.22, .2], [.22, .8], [.18, .95], [.06, 1], [0, 1.02]]), K.PAL.rust, tank, 0, 0, 0);\n  rig.helmet = helmet; rig.tank = tank; rig.kind = 'character';\n  return rig;\n});",
    'okene': "KIT.asset('okene', function (K, opts) {\n  var rig = K.human({ build: 'pear', skin: K.PAL.skin[3], hair: K.PAL.hair[1], hairStyle: 'short', top: 'tee', shirt: K.PAL.cream, pants: K.PAL.brown, nose: 1.45 });\n  rig.kind = 'character';\n  return rig;\n});",
    'reaching-hand': "KIT.asset('reaching-hand', function (K, opts) {\n  var root = new K.T.Group(), arm = new K.T.Group(); arm.position.set(0, 1.3, -.6); root.add(arm);\n  var limb = K.M(K.limb(.1, .08, .9), K.PAL.skin[3], arm, 0, 0, 0); limb.rotation.x = -Math.PI / 2;\n  var hand = new K.T.Group(); hand.position.set(0, 0, .9); arm.add(hand);\n  K.M(K.SPH, K.PAL.skin[3], hand, 0, 0, .06, .12, .09, .14);\n  K.M(K.SPH, K.PAL.skin[3], hand, .1, .02, .02, .035, .03, .07, 'thin');\n  return { root: root, kind: 'prop', arm: arm, hand: hand,\n    do: { reach: function (k, t) { arm.position.z = -.6 + K.ease(k) * .9; hand.rotation.x = Math.sin(t * 6) * .1 * (1 - k); } } };\n});",
    'torch': "KIT.asset('torch', function (K, opts) {\n  var root = new K.T.Group();\n  var body = K.M(K.limb(.06, .05, .42), K.PAL.charcoal, root, 0, .06, 0); body.rotation.x = Math.PI / 2;\n  K.M(K.lathe([[0, 0], [.09, 0], [.1, .06], [0, .06]]), K.PAL.gold, root, 0, .06, .42, 1, 1, 1, 'thin').rotation.x = Math.PI / 2;\n  K.glow(root, 0, .06, .5, .9, K.PAL.glowWarm, .7);\n  var grip = new K.T.Object3D(); grip.position.set(0, .06, .1); root.add(grip);\n  return { root: root, kind: 'prop', grip: grip };\n});",
    'cabin': "KIT.asset('cabin', function (K, opts) {\n  var root = new K.T.Group();\n  K.M(K.BOX, K.PAL.woodDark, root, 0, -.1, 0, 14, .2, 10);\n  K.M(K.BOX, K.PAL.moonlit, root, 0, 3, -5, 14, 6.4, .3);\n  K.M(K.BOX, K.PAL.night, root, -7, 3, 0, .3, 6.4, 10);\n  K.M(K.BOX, K.PAL.night, root, 7, 3, 0, .3, 6.4, 10);\n  for (var i = 0; i < 6; i++) K.M(K.BOX, K.PAL.night, root, -5.5 + i * 2.2, 3, -4.82, .08, 6, .08, 'thin');\n  var pipe = K.M(K.limb(.12, .12, 12), K.PAL.rust, root, -6, 5.2, -4.6); pipe.rotation.z = Math.PI / 2;\n  K.M(new K.T.TorusGeometry(.7, .1, 10, 28), K.PAL.gold, root, 2.6, 3.6, -4.8, 1, 1, 1, 'thin');\n  K.flat(new K.T.CircleGeometry(.62, 28), K.PAL.glowCyan, root, 2.6, 3.6, -4.82, 1, 1, 1, .9);\n  K.glow(root, 2.6, 3.6, -4.4, 4, K.PAL.glowCyan, .5);\n  var water = K.flat(new K.T.PlaneGeometry(14, 10), K.PAL.moonlight, root, 0, 4.4, 0, 1, 1, 1, .22); water.rotation.x = Math.PI / 2;\n  K.M(K.BOX, K.PAL.wood, root, -3.6, .5, -3.6, 2.2, 1, 1.1);\n  K.M(K.BOX, K.PAL.wood, root, 4.6, .9, -2.5, 1.2, 1.8, 2);\n  var lamp = new K.T.PointLight(0x5fa8a0, .8, 9); lamp.position.set(2.6, 3.4, -3.8); root.add(lamp);\n  return { root: root, kind: 'set', spots: { door: new K.T.Vector3(-5, 0, 2), center: new K.T.Vector3(0, 0, 0), corner: new K.T.Vector3(3, 0, -2.6), pocket: new K.T.Vector3(1.2, 0, -2.2) } };\n});"
  },
  shots: {
    'S01': "SHOT('S01', {\n  set: 'cabin',\n  cast: { diver: { at: 'door', turn: 'right', face: 'determined' }, torch: { at: [0, 0, 0] } },\n  camera: { framing: 'wide', on: 'diver', side: 'front-left', angle: 'high', move: 'crane-down' },\n  light: [{ mood: 'cold' }],\n  moves: [\n    { word: 'diver', who: 'diver', do: 'move', to: 'center', for: 2.5, arc: .3 },\n    { sec: 0, who: 'diver', do: 'hold', item: 'torch' },\n    { sec: 0, who: 'diver', do: 'float', height: .2 }\n  ],\n  sfx: [{ word: 'swims', sound: 'whoosh' }]\n});",
    'S02': "SHOT('S02', {\n  set: 'cabin',\n  cast: { diver: { at: 'center', turn: 20, face: 'neutral' }, torch: { at: [0, 0, 0] } },\n  camera: { framing: 'medium', on: 'diver', side: 'front-right', move: 'orbit-left' },\n  light: 'dark',\n  moves: [\n    { sec: 0, who: 'diver', do: 'hold', item: 'torch' },\n    { sec: .2, who: 'diver', do: 'turn', to: -40, for: 1.2 },\n    { word: 'bodies', who: 'diver', do: 'look', to: 'corner' }\n  ]\n});",
    'S03': "SHOT('S03', {\n  set: 'cabin',\n  cast: { diver: { at: 'center', turn: 30, face: 'neutral' }, 'reaching-hand': { at: 'corner', turn: -120 }, torch: { at: [0, 0, 0] } },\n  camera: { framing: 'full', on: ['diver', 'reaching-hand'], side: 'front', angle: 'low', move: 'push-in' },\n  focus: [{ on: 'reaching-hand' }, { word: 'grabs', on: 'diver', pull: .3 }],\n  light: [{ mood: 'dark' }, { word: 'hand', mood: 'danger', ease: .6 }],\n  moves: [\n    { sec: 0, who: 'diver', do: 'hold', item: 'torch' },\n    { word: 'reaches', who: 'reaching-hand', do: 'reach', for: 1.4 },\n    { word: 'grabs', who: 'diver', do: 'react', type: 'take' },\n    { word: 'grabs', who: 'diver', face: 'scared' },\n    { word: 'grabs', who: 'diver', do: 'look', to: 'reaching-hand' }\n  ],\n  sfx: [{ word: 'hand', sound: 'riser', length: 1.2 }, { word: 'grabs', sound: 'thud' }],\n  camera_note: 'push in as the hand comes'\n});",
    'S04': "SHOT('S04', {\n  set: 'cabin',\n  cast: { diver: { at: 'center', turn: 0, face: 'surprised', look: 'camera' } },\n  camera: { framing: 'close', on: 'diver', side: 'front', move: 'handheld', shake: [{ word: 'alive', amount: .05 }] },\n  light: 'danger',\n  moves: [{ word: 'alive', who: 'diver', do: 'react', type: 'shake' }],\n  sfx: [{ word: 'alive', sound: 'sting' }]\n});",
    'S05': "SHOT('S05', {\n  set: 'void',\n  cast: {},\n  camera: { framing: 'wide', move: 'drift' },\n  light: 'silhouette',\n  text: [{ sec: .1, say: '60 HOURS EARLIER', for: 2.5 }],\n  sfx: [{ sec: 0, sound: 'whoosh' }]\n});",
    'S06': "SHOT('S06', {\n  set: 'cabin',\n  cast: { okene: { at: 'pocket', turn: 15, face: 'scared' } },\n  camera: { framing: 'medium', on: 'okene', side: 'front-left', move: 'push-in' },\n  light: [{ mood: 'dark' }],\n  moves: [\n    { word: 'trapped', who: 'okene', do: 'look', to: 'camera' },\n    { word: 'pocket', who: 'okene', do: 'shake-head' }\n  ],\n  sfx: [{ word: 'trapped', sound: 'heartbeat' }]\n});"
  }
};
