/* DEMO 2 — "The Missing Cup": the test characters (kato, nia, hero, pear, noodle builds + the worm) in the paper garden. */
window.DEMO2 = {
  title: 'The Missing Cup',
  script: 'Every night, in a quiet paper garden, a cup goes missing. Kato is sure he left it right here. Nia thinks the farmer took it. The farmer blames the tall stranger. The stranger points at the strong man next door. Everyone argues. But the real thief is small, slow, and very pink. The worm just wanted somewhere dry to sleep.',
  plan: {
    title: 'The Missing Cup', sky: 'night',
    assets: [
      { name: 'garden', kind: 'set', difficulty: 2, size: 16, look: 'Moonlit paper garden: layered ridges, coral and teal paper trees, tufts, rocks, big moon.', parts: [], moves: [], spots: ['center', 'left', 'right', 'far-left', 'far-right', 'cup', 'tree'] },
      { name: 'farmer', kind: 'character', difficulty: 2, size: 2.4, look: 'Pear build, bald, moss tee, straw hat, big nose.', parts: ['hat'], moves: [] },
      { name: 'stranger', kind: 'character', difficulty: 2, size: 3.4, look: 'Noodle build: very tall and thin, long neck, charcoal coat, tall hair.', parts: [], moves: [] },
      { name: 'neighbour', kind: 'character', difficulty: 2, size: 3, look: 'Hero build: giant chest, rust tee, short hair.', parts: [], moves: [] },
      { name: 'worm', kind: 'creature', difficulty: 3, size: 1.2, look: 'Pink paper worm in round segments, big friendly face.', parts: ['head', 'neck'], moves: ['crawl'] },
      { name: 'cup', kind: 'prop', difficulty: 1, size: .3, look: 'Cream mug with a teal band and handle.', parts: [], moves: [], holdable: true }
    ],
    cuts: {
      main: [
        { id: 'M01', lines: [0, 1], set: 'garden', cast: ['cup'], show: 'Wide moonlit garden, the cup on the grass, then it is gone.', mood: 'cold', difficulty: 1 },
        { id: 'M02', lines: [2, 2], set: 'garden', cast: ['kato'], show: 'Kato walks in and points at the empty spot, annoyed.', mood: 'normal', difficulty: 2 },
        { id: 'M03', lines: [3, 3], set: 'garden', cast: ['nia', 'farmer'], show: 'Nia, sneaky, points at the farmer.', mood: 'warm', difficulty: 1 },
        { id: 'M04', lines: [4, 4], set: 'garden', cast: ['farmer', 'stranger'], show: 'Close on the farmer, shocked, he turns and points at the tall stranger.', mood: 'normal', difficulty: 2 },
        { id: 'M05', lines: [5, 5], set: 'garden', cast: ['stranger', 'neighbour'], show: 'Low angle: the tall stranger points at the strong neighbour.', mood: 'cold', difficulty: 2 },
        { id: 'M06', lines: [6, 6], set: 'garden', cast: ['kato', 'nia', 'farmer', 'stranger', 'neighbour'], show: 'Everyone argues in a wide shot.', mood: 'danger', difficulty: 2 },
        { id: 'M07', lines: [7, 8], set: 'garden', cast: ['cup', 'worm'], show: 'Under the tree, the worm peeks out of the cup.', mood: 'silhouette', difficulty: 2 },
        { id: 'M08', lines: [9, 9], set: 'garden', cast: ['cup', 'worm'], show: 'Close: the worm falls asleep in the cup.', mood: 'hope', difficulty: 1 }
      ]
    }
  },
  assets: {
    'garden': "KIT.asset('garden', function (K, opts) {\n  var root = new K.T.Group(), D = K.PAL.dio;\n  K.ground(root, { radius: 18 });\n  K.ridges(root, { z: -9 });\n  K.moon(root, 1.5, 6.5, -24, 2.6);\n  K.paperTree(root, -4.6, -2.6, { scale: 1.25 });\n  K.paperTree(root, 4.6, -3.4, { scale: 1.4, flip: true, leaves: [D.teal, D.tealDark] });\n  K.paperTree(root, -8, -5, { scale: 1.6 });\n  [[-6, -9, 1.2], [-1, -10, 1], [4, -10, 1.1]].forEach(function (c) { K.cloudSwirl(root, c[0], c[1] + 16, c[1], c[2]); });\n  for (var i = 0; i < 40; i++) { var x = (K.rnd() - .5) * 16, z = (K.rnd() - .5) * 9 - 2; if (Math.abs(x) < 4 && z > -1.5) continue; K.tuft(root, x, z, .8 + K.rnd() * .6, [D.coral, D.teal, D.salmon][i % 3]); }\n  K.rock(root, 2.8, 1.8, 1.2); K.rock(root, -3, 2.2, 1); K.rock(root, -4.2, -1.6, .8);\n  return { root: root, kind: 'set', spots: { center: new K.T.Vector3(0, 0, 0), left: new K.T.Vector3(-1.8, 0, .4), right: new K.T.Vector3(1.8, 0, .4), 'far-left': new K.T.Vector3(-3.4, 0, -.2), 'far-right': new K.T.Vector3(3.4, 0, -.2), cup: new K.T.Vector3(.4, 0, 1.4), tree: new K.T.Vector3(-3.8, 0, -1.4) } };\n});",
    'farmer': "KIT.asset('farmer', function (K, opts) {\n  var rig = K.human({ build: 'pear', skin: K.PAL.skin[2], hair: K.PAL.hair[2], hairStyle: 'bald', top: 'tee', shirt: K.PAL.moss, pants: K.PAL.brown, nose: 1.4 });\n  var hat = new K.T.Group(); hat.position.set(0, .84, -.02); rig.head.add(hat);\n  K.M(new K.T.CylinderGeometry(.62, .62, .03, 32), K.PAL.mustard, hat, 0, 0, 0);\n  K.M(K.SPH, K.PAL.mustard, hat, 0, .08, 0, .34, .2, .34);\n  K.M(new K.T.TorusGeometry(.35, .025, 8, 28), K.PAL.rust, hat, 0, .04, 0, 1, 1, 1, 'thin').rotation.x = Math.PI / 2;\n  rig.hat = hat; rig.kind = 'character';\n  return rig;\n});",
    'stranger': "KIT.asset('stranger', function (K, opts) {\n  var rig = K.human({ build: 'noodle', skin: K.PAL.skin[0], hair: K.PAL.hair[1], hairStyle: 'tall', top: 'tee', shirt: K.PAL.charcoal, pants: K.PAL.ink, nose: 1.3 });\n  rig.kind = 'character';\n  return rig;\n});",
    'neighbour': "KIT.asset('neighbour', function (K, opts) {\n  var rig = K.human({ build: 'hero', skin: K.PAL.skin[3], hair: K.PAL.hair[0], hairStyle: 'short', top: 'tee', shirt: K.PAL.rust, pants: K.PAL.charcoal, nose: 1.1 });\n  rig.kind = 'character';\n  return rig;\n});",
    'worm': "KIT.asset('worm', function (K, opts) {\n  var root = new K.T.Group(), body = new K.T.Group(); root.add(body);\n  var segs = [];\n  for (var i = 0; i < 11; i++) {\n    var r = .15 * (1 - .45 * i / 11), g = new K.T.Group(); g.position.set(0, r, -i * .11); body.add(g);\n    K.M(K.SPH, i % 2 ? 0x9c5060 : 0xb8646e, g, 0, 0, 0, r, r * .92, r * 1.12); segs.push(g);\n  }\n  var neck = new K.T.Group(); neck.position.set(0, .3, .16); body.add(neck);\n  var head = new K.T.Group(); head.scale.setScalar(.7); head.position.y = -.31; neck.add(head);\n  K.M(K.SPH, 0xb8646e, head, 0, .44, 0, .36, .41, .36);\n  var face = K.face(head, { r: .36, cy: .44, y: .5, gap: .14, size: 1.3, mouthY: .25 });\n  function crawl(t) { segs.forEach(function (g, i) { var r = .15 * (1 - .45 * i / 11); g.position.y = r + .08 * Math.pow(Math.max(0, Math.sin(t * 6.5 - i * .75)), 2); }); }\n  return { root: root, kind: 'creature', body: body, segs: segs, neck: neck, head: head, face: face,\n    do: { crawl: function (k, t) { crawl(t); } },\n    idle: function (t) { neck.rotation.x = Math.sin(t * 1.5) * .08; } };\n});",
    'cup': "KIT.asset('cup', function (K, opts) {\n  var root = new K.T.Group();\n  K.M(K.lathe([[0, 0], [.13, 0], [.14, .03], [.15, .26], [.13, .26], [.12, .04], [0, .04]]), K.PAL.cream, root, 0, 0, 0);\n  K.M(new K.T.CylinderGeometry(.152, .152, .05, 32, 1, true), K.PAL.teal, root, 0, .17, 0, 1, 1, 1, 'thin');\n  var h = K.M(new K.T.TorusGeometry(.07, .022, 8, 20), K.PAL.cream, root, .17, .14, 0, 1, 1, 1, 'thin');\n  var grip = new K.T.Object3D(); grip.position.set(.2, .14, 0); root.add(grip);\n  return { root: root, kind: 'prop', grip: grip, handle: h };\n});"
  },
  shots: {
    'M01': "SHOT('M01', {\n  set: 'garden', air: 'dust',\n  cast: { cup: { at: 'cup' } },\n  camera: { framing: 'wide', angle: 'high', move: 'crane-down', height: -1.1 },\n  light: [{ mood: 'cold' }],\n  moves: [{ word: 'missing', who: 'cup', do: 'vanish', for: .4 }],\n  sfx: [{ word: 'missing', sound: 'pop' }]\n});",
    'M02': "SHOT('M02', {\n  set: 'garden',\n  cast: { kato: { at: 'left', turn: 'right', face: 'annoyed' } },\n  camera: { framing: 'medium', on: 'kato', side: 'front-right', move: 'push-in' },\n  light: 'normal',\n  moves: [\n    { sec: 0, who: 'kato', do: 'walk', to: 'center', for: 1.4 },\n    { word: 'right', who: 'kato', do: 'turn', to: 'camera', for: .3 },\n    { word: 'here', who: 'kato', do: 'point', to: 'cup', for: 1.2 },\n    { word: 'sure', who: 'kato', do: 'nod' }\n  ],\n  sfx: [{ sec: 0, sound: 'step' }, { sec: .6, sound: 'step' }]\n});",
    'M03': "SHOT('M03', {\n  set: 'garden',\n  cast: { nia: { at: 'right', turn: -15, face: 'sneaky' }, farmer: { at: 'far-left', turn: 30, face: 'neutral' } },\n  camera: { framing: 'medium', on: 'nia', side: 'front-right', move: 'drift' },\n  focus: [{ on: 'nia' }],\n  light: 'warm',\n  moves: [\n    { word: 'farmer', who: 'nia', do: 'point', to: 'farmer', for: 1.6 },\n    { word: 'thinks', who: 'nia', do: 'look', to: 'farmer' }\n  ],\n  sfx: [{ word: 'farmer', sound: 'swish' }]\n});",
    'M04': "SHOT('M04', {\n  set: 'garden',\n  cast: { farmer: { at: 'far-left', turn: 20, face: 'surprised' }, stranger: { at: 'far-right', turn: -30 } },\n  camera: { framing: 'medium', on: 'farmer', side: 'front', angle: 'low', move: 'push-in' },\n  light: 'normal',\n  moves: [\n    { sec: 0, who: 'farmer', do: 'react', type: 'take' },\n    { word: 'blames', who: 'farmer', face: 'annoyed' },\n    { word: 'tall', who: 'farmer', do: 'look', to: 'stranger' }\n  ],\n  sfx: [{ sec: .05, sound: 'pop' }]\n});",
    'M05': "SHOT('M05', {\n  set: 'garden',\n  cast: { stranger: { at: 'far-right', turn: -60, face: 'sneaky' }, neighbour: { at: 'left', turn: 40, face: 'neutral' } },\n  camera: { framing: 'full', on: ['stranger', 'neighbour'], side: 'front', angle: 'low', move: 'crane-up' },\n  focus: [{ on: 'stranger' }, { word: 'strong', on: 'neighbour', pull: .5 }],\n  light: 'cold',\n  moves: [\n    { word: 'points', who: 'stranger', do: 'point', to: 'neighbour', for: 2 },\n    { word: 'strong', who: 'neighbour', face: 'surprised' },\n    { word: 'strong', who: 'neighbour', do: 'react', type: 'take' }\n  ]\n});",
    'M06': "SHOT('M06', {\n  set: 'garden',\n  cast: {\n    kato: { at: 'left', turn: 30, face: 'annoyed' }, nia: { at: 'center', turn: 0, face: 'annoyed' },\n    farmer: { at: 'right', turn: -30, face: 'annoyed' }, stranger: { at: 'far-right', turn: -40, face: 'determined' },\n    neighbour: { at: 'far-left', turn: 40, face: 'annoyed' }\n  },\n  camera: { framing: 'wide', side: 'front', move: 'orbit-left', shake: [{ word: 'argues', amount: .04 }] },\n  light: 'danger',\n  moves: [\n    { sec: 0, who: 'kato', do: 'talk', for: 1.2 }, { sec: .1, who: 'farmer', do: 'shake-head' },\n    { sec: .2, who: 'neighbour', do: 'wave', for: 1 }, { sec: 0, who: 'nia', do: 'talk', for: 1.2 },\n    { word: 'argues', who: 'stranger', do: 'shake' }\n  ],\n  sfx: [{ word: 'argues', sound: 'thud' }]\n});",
    'M07': "SHOT('M07', {\n  set: 'garden',\n  cast: { cup: { at: 'tree', turn: 30 }, worm: { at: 'tree', y: .2, size: .4, turn: 20, face: 'sneaky' } },\n  camera: { framing: 'medium', on: ['cup', 'worm'], side: 'front-right', angle: 'eye', move: 'push-in' },\n  focus: [{ on: ['cup', 'worm'] }],\n  light: [{ mood: 'silhouette' }, { word: 'pink', mood: 'hope', ease: .8 }],\n  moves: [\n    { sec: 0, who: 'worm', do: 'appear', for: .5 },\n    { word: 'slow', who: 'worm', do: 'crawl', for: 2 },\n    { word: 'pink', who: 'worm', face: 'happy' }\n  ],\n  sfx: [{ word: 'thief', sound: 'sting' }, { word: 'pink', sound: 'tada' }]\n});",
    'M08': "SHOT('M08', {\n  set: 'garden', air: 'dust',\n  cast: { cup: { at: 'tree', turn: 30 }, worm: { at: 'tree', y: .2, size: .4, turn: 20, face: 'happy', look: 'camera' } },\n  camera: { framing: 'medium', on: ['cup', 'worm'], side: 'front', move: 'pull-out' },\n  light: 'hope',\n  moves: [\n    { word: 'dry', who: 'worm', face: 'sleepy' },\n    { word: 'sleep', who: 'worm', do: 'nod' }\n  ],\n  sfx: [{ word: 'sleep', sound: 'snore', length: 1.6 }]\n});"
  }
};
